apiVersion: v1
kind: Service
metadata:
  name: kube-node-app-service
spec:
  selector:
    app: kube-node-app
  ports:
    - port: 4000
      targetPort: 3000
      nodePort: 31234
  type: NodePort
